# Generated by Django 4.2.6 on 2023-10-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_address_street_remove_address_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
